#!/bin/sh

# Enable huge pages if more than 35 GB RAM
if [ "$[$(grep MemTotal /proc/meminfo | awk '{ print $2 }') / 1024]" -gt "5000" ]; then
    echo madvise > /sys/kernel/mm/transparent_hugepage/enabled
fi
